name: GNU/Linux & macOS Build

# Controls when the action will run. Triggers the workflow on push or
# pull request events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run
# sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    # Steps represent a sequence of tasks that will be executed as part
    # of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job
      # can access it
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.5.0
        env:
          CIBW_ARCHS_MACOS: x86_64 universal2
          CIBW_ARCHS_LINUX: auto
          CIBW_SKIP: '*-win32 *-musllinux_*'
          CIBW_BEFORE_ALL_LINUX: apt-get update; apt-get install -y libpcsclite-dev python3-all-dev python3-setuptools swig
          CIBW_BEFORE_ALL_MACOS: brew install swig
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_24
          CIBW_MANYLINUX_I686_IMAGE: manylinux_2_24
          CIBW_MANYLINUX_PYPY_X86_64_IMAGE: manylinux_2_24
          CIBW_MANYLINUX_PYPY_I686_IMAGE: manylinux_2_24

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
